---
  version: "3.8"
  services:
    mundiapp:
      image: gabrielguidi/mundiapp
      build:
        context: .
      networks: 
        - net
      ports:
        - 32771:443
        - 32770:80

    rabbitmq:
      image: "rabbitmq:3-management"
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq" 
        RABBITMQ_DEFAULT_VHOST: "/"
      ports:
        - "15672:15672"
        - "5672:5672"
      networks: 
        - net

  networks: 
    net:
      driver: bridge